name: tum_lint

on:
  push:
    branches:
      - 'master'
      - 'michael/**'
      - 'lukas/**'
      - 'yoshi/**'
      - 'simon/**'
      - 'philip/**'
      - 'julius/**'
      - 'javier/**'
      - 'feyza/**'
      - 'jakob/**'
      - 'mohammadreza/**'
      - 'particle/**'
      - 'softwarelab/**'
      - 'catalyst/**'
  pull_request:
    branches: [ master ]

jobs:
  fortran-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v4

    - name: Install whatthepatch
      run: |
        python3 -m pip install whatthepatch

    - name: Lint
      run: |
        git fetch origin master
        git diff origin/master..HEAD | ./ci/lint-fortran.py --stdin
